@startuml
actor Дитина


loop "До поки дитина грає"
    "Гра"->"Дитина": картка з дією
    activate "Гра"
    deactivate "Гра"
    ...
    Дитина -> "Гра": вхідний сигнал
    activate "Гра"
    "Гра" -> "Розпізновач жестів": вхідний сигнал
     activate  "Розпізновач жестів"
        "Розпізновач жестів" -> "Метод розпізнання": вхідний сигнал
        activate "Метод розпізнання"
            create "Вихідний сигнал"
            "Метод розпізнання" -> "Вихідний сигнал"
            activate "Вихідний сигнал"
            return
        return "Вихідний сигнал"


        "Розпізновач жестів" -> "Розпізновач жестів": скорегувати дані

        "Розпізновач жестів" -> "Візуалізатор": відобразити жест
        activate "Візуалізатор"
        return "повернути керунвання"
     return Вихідний сигнал
     "Гра" ->    "Гра": Звірка з \nправильною \nвідподдю
     return Правленьність\n відповіді\n користовуча
end
@enduml