@startuml


interface "Метод Розпізнання" {
    зброс()
    тренувати(ВхіднийСигнал [] тренувальниНабір, ВхіднийСигнал тестувальний)
    ВихіднийСигнал розпізнати(ВхіднийСигнал сигнал)
}

class Візуалізатор{
    відобразити(ВхіднийСигнал вхіднийСигнал)
}

abstract class Розпізновач {
    Pair<ВхіднийСигнал,ВихіднийСигнал>[] історія;
    розпізнати(Вхідний сигнал);
    відобразити();
}


class "Розпізновач Жестів" {
    Pair<ВхіднийСигнал,ВихіднийСигнал>[] історія;
    -ВихіднийСигнал аналізуватиІсторію(ВхіднийСигнал сигнал, ВихіднийСигнал кандидат)
    +розпізнати(Вхідний сигнал);
    +відобразити();
}


"Розпізновач Жестів" --|> Розпізновач
"Метод Розпізнання" "1" --o "1" "Розпізновач Жестів"
"Візуалізатор" "1" --o "1" "Розпізновач Жестів"
Гра --> "Розпізновач": подає  ВхіднийСигнал

ВхіднийСигнал "1" --o "n" "Розпізновач"
ВхіднийСигнал -- "Метод Розпізнання": розпізнаєтся
"Метод Розпізнання" <.. ВихіднийСигнал: залежить від методу
"Розпізновач" <.. ВихіднийСигнал: залежить від історії

@enduml