@startuml
scale 3
actor Система

Система -> Жест **
activate Жест
Жест -> СкелетнаГруппа **

activate СкелетнаГруппа
return "долонь"

loop for(int i = 0; i< 5; i++)
   Жест -> СкелетнаГруппа
   activate СкелетнаГруппа
   СкелетнаГруппа -> СкелетнаГруппа ++: new СкелетнаГруппа()
   loop  for(int j = 0; j< 3; j++)
        СкелетнаГруппа -> Кістка **: додати фалангу пальцю
        activate Кістка
        return
        deactivate СкелетнаГруппа
   end

   return скелет
end
return жест
Система -> Жест ++: стиснути руки на 90%
Жест -> Скелет++: стиснути руку на 90%
return
return: жест
Система -> Жест ++: відобразити
Жест -> Скелет++: відобразити
return
return: жест
@enduml