@startuml
scale 3
class Жест {
    відобразити()
    Жест()
}

interface "Скелет" as Skeletone {

    cтиснути(ступінь);
    намалювати();
    int отриматиСтупіньСтиснутості()
}
class "Кістка" as Bone {
     cтупіньСтинуності
     cтиснути(ступінь);
     намалювати();
     int отриматиСтупіньСтиснутості();
}
class "КістковаГрупа" as Falang {
      додати(Скелет скелет);
      отриматиСкелети();
      видалити(Скелет скелет);
      намалювати();
      cтиснути(ступінь);
      int отриматиСтупіньСтиснутості();
}

Skeletone <|-- Bone
Skeletone <|-- Falang

Жест o-- Skeletone

note as signNote
    КістковаГрупа великийПалець = new КістковаГрупа() ;
    "..."
    КістковаГрупа мізинець = new КістковаГрупа();
    КістковаГрупа долонь = new КістковаГрупа();
    долонь.додати(великийПалець);
    "..."
    foreach(КістковаГрупа палець in долонь){
        for(int i=0; i < 3; i++) {
            палець.додати(new Кістка())
        }
    }

    Скелет рука = долонь;
    рука.ступінь(90);

end note

Жест .. signNote

@enduml