@startuml
actor Розпізновач

scale 3

Розпізновач --> МетодФасад: ініціалюзувати
activate МетодФасад


create НейронаМережаФабрикаВсеТілоImpl
МетодФасад -> НейронаМережаФабрикаВсеТілоImpl: "створити фабрику для всього тіла"
activate НейронаМережаФабрикаВсеТілоImpl
return

create НейронаМережаФабрикаРукиТаГоловаImpl
МетодФасад -> НейронаМережаФабрикаРукиТаГоловаImpl:  "створити фабрику для рук та голови"
activate НейронаМережаФабрикаРукиТаГоловаImpl
return

create НейронаМережаФабрикаТількиРукиImpl
МетодФасад -> НейронаМережаФабрикаТількиРукиImpl: "створити фабрику для тільки рук"
activate НейронаМережаФабрикаТількиРукиImpl
return


return initializedObj

    loop foreach ТипМетоду
    loop foreach ТипСкелету
    Розпізновач --> МетодФасад:createModel(типСкелету, типМетоду)
    activate МетодФасад


    alt типСкелету == FullBody

        alt case типМетоду == RNN
            МетодФасад -> НейронаМережаФабрикаВсеТілоImpl: "create RNN"
            activate НейронаМережаФабрикаВсеТілоImpl
            create "rnn:НейроноМережевийМетод"
            НейронаМережаФабрикаВсеТілоImpl -> "rnn:НейроноМережевийМетод"
            activate "rnn:НейроноМережевийМетод"

            return model

        else case типМетоду == GRU
            МетодФасад -> НейронаМережаФабрикаВсеТілоImpl: "create GRU"
            create "gru:НейроноМережевийМетод"
            НейронаМережаФабрикаВсеТілоImpl -> "gru:НейроноМережевийМетод"
            activate "gru:НейроноМережевийМетод"
            return model
        else case типМетоду == TGCN
            МетодФасад -> НейронаМережаФабрикаВсеТілоImpl:  "create TGCN"
            create "tgcn:НейроноМережевийМетод"
            НейронаМережаФабрикаВсеТілоImpl -> "tgcn:НейроноМережевийМетод"
            activate "tgcn:НейроноМережевийМетод"
            return model
    end

    return fullBodyNeuralNetworkModel
    else типСкелету == HandsAndHead
        alt case типМетоду == RNN
            МетодФасад -> НейронаМережаФабрикаРукиТаГоловаImpl: "create RNN"
            activate НейронаМережаФабрикаРукиТаГоловаImpl
            create "rnn:НейроноМережевийМетод"
            НейронаМережаФабрикаРукиТаГоловаImpl -> "rnn:НейроноМережевийМетод"
            activate "rnn:НейроноМережевийМетод"
            return model

        else  case типМетоду == GRU
            МетодФасад -> НейронаМережаФабрикаРукиТаГоловаImpl: "create GRU"
            create "gru:НейроноМережевийМетод"
            НейронаМережаФабрикаРукиТаГоловаImpl -> "gru:НейроноМережевийМетод"
            activate "gru:НейроноМережевийМетод"
            return model
    else  case типМетоду == TGCN
        МетодФасад ->  НейронаМережаФабрикаРукиТаГоловаImpl: "create TGCN"
        create "tgcn:НейроноМережевийМетод"
        НейронаМережаФабрикаРукиТаГоловаImpl -> "tgcn:НейроноМережевийМетод"
        activate "tgcn:НейроноМережевийМетод"
        return model
    end
    return handsAndHeadNeuralNetworkModel
    else типСкелету == HandsOnly
        alt case типМетоду == RNN
            МетодФасад -> НейронаМережаФабрикаТількиРукиImpl: "create RNN"
            activate НейронаМережаФабрикаТількиРукиImpl
            create "rnn:НейроноМережевийМетод"
            НейронаМережаФабрикаТількиРукиImpl -> "rnn:НейроноМережевийМетод"
            activate "rnn:НейроноМережевийМетод"
            return model

        else  case типМетоду == GRU


            МетодФасад -> НейронаМережаФабрикаТількиРукиImpl:  "create GRU"
            create "gru:НейроноМережевийМетод"
            НейронаМережаФабрикаТількиРукиImpl -> "gru:НейроноМережевийМетод"
            activate "gru:НейроноМережевийМетод"
            return model
        else  case типМетоду == TGCN
            МетодФасад -> НейронаМережаФабрикаТількиРукиImpl: "create TGCN"
            create "tgcn:НейроноМережевийМетод"
            НейронаМережаФабрикаТількиРукиImpl -> "tgcn:НейроноМережевийМетод"
            activate "tgcn:НейроноМережевийМетод"
            return model
        end
        return тілкиРукиНейроноМережевийМетод
        return нейроноМережевийМетод

    end
    end
    end

@enduml