@startuml
actor Розпізновач


Розпізновач --> МетодФасад: ініціалюзувати
activate МетодФасад


МетодФасад --> НейронаМережеваФабрика
activate НейронаМережеваФабрика

create НейронаМережаФабрикаВсеТілоImpl
НейронаМережеваФабрика -> НейронаМережаФабрикаВсеТілоImpl: "створити фабрику для всього тіла"
activate НейронаМережаФабрикаВсеТілоImpl
return

create НейронаМережаФабрикаРукиТаГоловаImpl
НейронаМережеваФабрика -> НейронаМережаФабрикаРукиТаГоловаImpl:  "створити фабрику для рук та голови"
activate НейронаМережаФабрикаРукиТаГоловаImpl
return

create НейронаМережаФабрикаТількиРукиImpl
НейронаМережеваФабрика -> НейронаМережаФабрикаТількиРукиImpl: "створити фабрику для тільки рук"
activate НейронаМережаФабрикаТількиРукиImpl
return

return return фабрика impl`s
return initializedObj

    loop foreach ТипМетоду
    loop foreach ТипСкелету
    Розпізновач --> МетодФасад:createModel(типСкелету, типМетоду)
    activate МетодФасад

    МетодФасад --> НейронаМережеваФабрика:
    activate НейронаМережеваФабрика
    alt типСкелету == FullBody

        alt case типМетоду == RNN

            МетодФасад -> НейронаМережеваФабрика: "create RNN"
            НейронаМережеваФабрика -> НейронаМережаФабрикаВсеТілоImpl: "create RNN"
            activate НейронаМережаФабрикаВсеТілоImpl
            create "rnn:НейроноМережевийМетод"
            НейронаМережаФабрикаВсеТілоImpl -> "rnn:НейроноМережевийМетод"
            activate "rnn:НейроноМережевийМетод"
            return model

        else case типМетоду == GRU

            МетодФасад -> НейронаМережеваФабрика : "create GRU"
            НейронаМережеваФабрика -> НейронаМережаФабрикаВсеТілоImpl: "create GRU"
            create "gru:НейроноМережевийМетод"
            НейронаМережаФабрикаВсеТілоImpl -> "gru:НейроноМережевийМетод"
            activate "gru:НейроноМережевийМетод"
            return model
        else case типМетоду == TGCN

            МетодФасад -> НейронаМережеваФабрика: "create TGCN"
            НейронаМережеваФабрика -> НейронаМережаФабрикаВсеТілоImpl:  "create TGCN"
            create "tgcn:НейроноМережевийМетод"
            НейронаМережаФабрикаВсеТілоImpl -> "tgcn:НейроноМережевийМетод"
            activate "tgcn:НейроноМережевийМетод"
            return model
    end

    return fullBodyNeuralNetworkModel
    else типСкелету == HandsAndHead
        alt case типМетоду == RNN

            МетодФасад -> НейронаМережеваФабрика: "create RNN"
            НейронаМережеваФабрика -> НейронаМережаФабрикаРукиТаГоловаImpl: "create RNN"
            activate НейронаМережаФабрикаРукиТаГоловаImpl
            create "rnn:НейроноМережевийМетод"
            НейронаМережаФабрикаРукиТаГоловаImpl -> "rnn:НейроноМережевийМетод"
            activate "rnn:НейроноМережевийМетод"
            return model

        else  case типМетоду == GRU

            МетодФасад -> НейронаМережеваФабрика: "create GRU"
            НейронаМережеваФабрика -> НейронаМережаФабрикаРукиТаГоловаImpl: "create GRU"
            create "gru:НейроноМережевийМетод"
            НейронаМережаФабрикаРукиТаГоловаImpl -> "gru:НейроноМережевийМетод"
            activate "gru:НейроноМережевийМетод"
            return model
    else  case типМетоду == TGCN

        МетодФасад -> НейронаМережеваФабрика: "create TGCN"
        НейронаМережеваФабрика ->  НейронаМережаФабрикаРукиТаГоловаImpl: "create TGCN"
        create "tgcn:НейроноМережевийМетод"
        НейронаМережаФабрикаРукиТаГоловаImpl -> "tgcn:НейроноМережевийМетод"
        activate "tgcn:НейроноМережевийМетод"
        return model
    end
    return handsAndHeadNeuralNetworkModel
    else типСкелету == HandsOnly
        alt case типМетоду == RNN

            МетодФасад -> НейронаМережеваФабрика: "create RNN"
            НейронаМережеваФабрика -> НейронаМережаФабрикаТількиРукиImpl: "create RNN"
            activate НейронаМережаФабрикаТількиРукиImpl
            create "rnn:НейроноМережевийМетод"
            НейронаМережаФабрикаТількиРукиImpl -> "rnn:НейроноМережевийМетод"
            activate "rnn:НейроноМережевийМетод"
            return model

        else  case типМетоду == GRU

            МетодФасад -> НейронаМережеваФабрика: "create GRU"
            НейронаМережеваФабрика -> НейронаМережаФабрикаТількиРукиImpl:  "create GRU"
            create "gru:НейроноМережевийМетод"
            НейронаМережаФабрикаТількиРукиImpl -> "gru:НейроноМережевийМетод"
            activate "gru:НейроноМережевийМетод"
            return model
        else  case типМетоду == TGCN

            МетодФасад -> НейронаМережеваФабрика: "create TGCN"
            НейронаМережеваФабрика -> НейронаМережаФабрикаТількиРукиImpl: "create TGCN"
            create "tgcn:НейроноМережевийМетод"
            НейронаМережаФабрикаТількиРукиImpl -> "tgcn:НейроноМережевийМетод"
            activate "tgcn:НейроноМережевийМетод"
            return model
        end


        return тілкиРукиНейроноМережевийМетод
        return нейроноМережевийМетод

    end
     return методи
    end
    end

@enduml