@startuml

actor Дитина

Дитина -> Меню: обрати в гру алфавіт
activate Меню
    create БудівельникГриАлфавіт
    Меню -> БудівельникГриАлфавіт: new БудівельникГриАлфавіт()
    activate БудівельникГриАлфавіт
    return будівельник
    create Директор
    Меню -> Директор: new Директор()
    activate Директор
    return директор
    Меню -> Директор: побудувати гру алфавіт
    activate Директор
        Директор -> БудівельникГриАлфавіт: додати Оцінювач
        activate  БудівельникГриАлфавіт
        return boolean додалось

        Директор -> БудівельникГриАлфавіт: додати розпізновач
        activate  БудівельникГриАлфавіт
        return boolean додалось

         Директор -> БудівельникГриАлфавіт: додати метод розпізання
         activate  БудівельникГриАлфавіт
         return boolean додалось

         Директор -> БудівельникГриАлфавіт: додати збірник статистики
         activate  БудівельникГриАлфавіт
         return boolean додалось

    return передати управління
    Меню -> БудівельникГриАлфавіт: отримати результат
    activate БудівельникГриАлфавіт
    return гра алфавіт
    return гра
@enduml