@startuml

class Директор {
    побудуватиГруАлфавіт(Будівник будівник);
    побудуватиГруПари(Будівник будвівник);
}

abstract class БудівельникГри{
    очистити()
    додатиРозпізновач()
    додатиМетодРозпізновання()
    встановитиПравила(Правила[] правила)
    додатиОцінювач(Оцінювач оцінювач)
    додатиЗбірникСтатистики(Статистика статистика)
}

class БудівельникГриАлфавіт{
  очистити()
  додатиРозпізновач()
  додатиМетодРозпізновання()
  встановитиПравила(Правила[] правила)
  додатиОцінювач(Оцінювач оцінювач)
  додатиЗбірникСтатистики(Статистика статистика)
  "Гра алфавіт"  отриматиРезлутат()
}

class БудівельникГриПари{
  очистити()
  додатиРозпізновач()
  додатиМетодРозпізновання()
  встановитиПравила(Вихідний сигнал правила)
  додатиОцінювач(Оцінювач оцінювач)
  додатиЗбірникСтатистики(Статистика статистика)
  "Гра пари"  отриматиРезлутат()
}

abstract class Гра {
}





БудівельникГриПари --|> БудівельникГри
БудівельникГриАлфавіт --|> БудівельникГри


БудівельникГри --o Директор
Гра <|-- "Гра алфавіт"
БудівельникГриАлфавіт -> "Гра алфавіт"
Гра <|-- "Гра пари"
БудівельникГриПари  -> "Гра пари"


Меню -> БудівельникГриАлфавіт
Меню -> Директор

@enduml