@startuml
skinparam dpi 850

actor Дитина
create "гра Алфавіт"
Дитина -> "гра Алфавіт": гра(алфавіт, складність легка, метод розпізновання RNN)
    activate "гра Алфавіт"
        create "Розпізнавач дактилів"
        "гра Алфавіт" -> "Розпізнавач дактилів"
            activate "Розпізнавач дактилів"
                create "Метод RNN"
                "Розпізнавач дактилів" ->  "Метод RNN"
                    activate  "Метод RNN"
                    return ":RNN"
                            return "розпізновач"



        create  "Оцінювач"
        "гра Алфавіт" ->  "Оцінювач": Складність, перелік правил
        activate "Оцінювач"
        return "Оцінювач"
            "гра Алфавіт" -> "Статистика гри"
                activate "Статистика гри"
                return "статистика гри"
                "гра Алфавіт" -> "Статистика методу"
                activate "Статистика методу"
                return "статистика методу"
         return гра

"Дитина" ->  "гра Алфавіт" : гратись
activate "гра Алфавіт"
    loop "до поки триває гра за умовами"
        "Дитина" -> "гра Алфавіт": Дактиль
        "гра Алфавіт" -> "Розпізнавач дактилів": рух гравця
        activate "Розпізнавач дактилів"
            "Розпізнавач дактилів" -> "Метод RNN": вхідний сигнал
            activate "Метод RNN"
                "Метод RNN" -> "Вихідний сигнал"
                activate "Вихідний сигнал"
                return
            return вихідний сигнал
            "Розпізнавач дактилів" ->  "Вихідний сигнал": скорегувати за часом виконання
            activate "Вихідний сигнал"
            return
        return вихідний сигнал
        "гра Алфавіт" -> Оцінювач: оцінити вихідний сигнал на відповідність правилам
        activate Оцінювач
            create Оцінка
            Оцінювач -> Оцінка
            activate Оцінка
            return оцінка
            Оцінювач -> Оцінювач: записати
            activate Оцінювач
            deactivate Оцінювач
        return оцінка
        "гра Алфавіт" ->  "Статистика методу": вхідний/вихідний сигнал
         activate "Статистика методу"
            create "Статистичний запис"
            "Статистика методу" -> "Статистичний запис" : записати
            activate "Статистичний запис"
            return
         return
         "гра Алфавіт" ->  "Статистика гри": оцінка
         activate "Статистика гри"
             create "Статистичний запис"
                       "Статистика гри" -> "Статистичний запис": записати
                        activate "Статистичний запис"
                        return

         return

    end
    return успіх гри

@enduml