@startuml

actor Client

Client -> Розпізновач: доступні методи

activate Розпізновач



 alt швидка обробка

     Розпізновач -> КоллекціяМетодів
     activate КоллекціяМетодів
     create КоллеціяМассив
        КоллекціяМетодів -> КоллеціяМассив
        activate КоллеціяМассив
            КоллеціяМассив -> Ітератор
            activate Ітератор
                create ІтераторМассиву
                Ітератор -> ІтераторМассиву
                activate ІтераторМассиву
                return
            return
     return

 else обробка зі змінами
     Розпізновач -> КоллекціяМетодів
     create "КоллеціяЗв'язнийСписок"
        КоллекціяМетодів -> "КоллеціяЗв'язнийСписок"
        activate "КоллеціяЗв'язнийСписок"
            "КоллеціяЗв'язнийСписок" -> "Ітератор"
            activate Ітератор
                create "ІтераторЗв'язнийСписок"
                "Ітератор" -> "ІтераторЗв'язнийСписок"
                activate "ІтераторЗв'язнийСписок"
                return
        return
     return

 end
 return
 Розпізновач -> КоллекціяМетодів
 activate КоллекціяМетодів
    loop foreach метод
        create Метод
        КоллекціяМетодів -> Метод
        activate Метод
        return
    end
 return
 return

 loop while ВхіднийСигнал != null || ВхіднийСигнал == err
 Client -> Розпізновач: ВхіднийСигнал
 activate Розпізновач
    alt єНаступний == true
        Розпізновач -> КоллекціяМетодів
        activate КоллекціяМетодів
            КоллекціяМетодів -> Ітератор
            activate Ітератор
                Ітератор -> Метод
                activate Метод
                return
            return
        return
    else єНаступний == false
        Розпізновач -> КоллекціяМетодів
            activate КоллекціяМетодів
                КоллекціяМетодів -> Ітератор
                activate Ітератор
                return err Кінець колекції
            return
    end
    return ВихіднийСигнал
 end

@enduml