@startuml

class Розпізновач {
    обробитиШвибдко()
    обробитиЗіЗмінами()
}

class Ітератор {
   Метод наступний();
   bool чиЄНаступний();
}

abstract class КоллекціяМетодів {
   Ітератор створитиІтератор()
   додатиМетод()
   видалитиМетод()
}

class КоллеціяЗв'язнийСписок{
    Ітератор створитиІтератор()
    додатиМетод()
    видалитиМетод()
}

class КоллеціяМассив{
    Ітератор створитиІтератор()
     додатиМетод()
     видалитиМетод()
}

class ІтераторМассиву {
     Метод наступний();
     bool єНаступний();
}


class ІтераторЗв'язнийСписок {
     Метод наступний();
     bool чиЄНаступний();
}


"КоллеціяЗв'язнийСписок" --|> КоллекціяМетодів
"КоллеціяМассив" --|> КоллекціяМетодів
"ІтераторЗв'язнийСписок" --|> Ітератор
"ІтераторМассиву" --|> Ітератор
КоллекціяМетодів o--> Метод
Ітератор --> Метод
Ітератор <-- Розпізновач
Ітератор <-- КоллекціяМетодів
"КоллеціяЗв'язнийСписок" <--> "ІтераторЗв'язнийСписок"
"КоллеціяМассив" <--> "ІтераторМассиву"
Розпізновач --> "КоллеціяЗв'язнийСписок"
Розпізновач --> КоллеціяМассив
@enduml