@startuml

actor Дитина

Дитина -> "Меню": обрати гру
activate  "Меню"
Меню -> "Оцінювач"
activate  "Оцінювач"
    create "Гра"
    "Оцінювач" -> Гра: ініц.
    activate Гра
        create Розпізновач
        Гра -> Розпізновач
        activate Розпізновач
        return "розпізновач"
        return гра
    return
return гра
loop до поки дитина грає
Дитина -> Гра
        activate Гра
            Гра -> Розпізновач
            activate Розпізновач
                create  "Вихідний сигнал"
                Розпізновач  -> "Вихідний сигнал": формує
                activate  "Вихідний сигнал"
                return
                    Розпізновач  -> "Вихідний сигнал": надає Оцінювач
                    activate  "Вихідний сигнал"
                        "Вихідний сигнал" -> "Результат дії \n користувача": додати Оцінювач
                        activate  "Результат дії \n користувача"
                        return
                        return
                  Розпізновач  -> "Вихідний сигнал": змінює стан
                  deactivate  Розпізновач
                                activate  "Вихідний сигнал"
                                 "Вихідний сигнал" -> "Результат дії \n користувача": сповістити
                                 activate  "Результат дії \n користувача"
                                    "Результат дії \n користувача" -> "Результат дії \n користувача": сповістити всіх
                                    activate  "Результат дії \n користувача"
                                        "Результат дії \n користувача" -> Гра: оновити викорстанний сигнал
                                         deactivate "Результат дії \n користувача"
                                 deactivate "Результат дії \n користувача"
                deactivate  "Вихідний сигнал"
        Гра -> Гра: скорегувати стан
        return Результат дії
end
@enduml