@startuml



interface  "Результат дії \n користувача" as result{
    додатиОцінювач(Оцінювач оцінювач);
    видалитиОцінювач(Оцінювач оцінювач);
    сповістити()
}

interface  Оцінювач:Observer {
    Оцінка оцінити(ВихіднийСигнал сигнал)
}
class Гра:ConcreteObserver {
    оцінити(ВхіднийСигнал )
    грати()
}
class "Вихідний сигнал:ConcreteObservable"{
        Оцінювач[] оцінювач;
        додатиОцінювач(Оцінювач оцінювач);
        видалитиОцінювач(Оцінювач оцінювач);
        сповістити()
}
class "Розпізновач" {
    Гра контекст
    ропізнати(ВхіднийСигнал сигнал)
}
"Розпізновач" <-- "Вхідний сигнал":Розпізнаєтся
"Розпізновач" "1" --> "n"  "Вихідний сигнал:ConcreteObservable":Видає


"Вихідний сигнал:ConcreteObservable" --|> result
"Оцінювач:Observer" --> Оцінка: генерує
"Оцінювач:Observer" <|-- "Гра:ConcreteObserver"
"Гра:ConcreteObserver" o-- Розпізновач
"Вихідний сигнал:ConcreteObservable" --o "Оцінювач:Observer"
"Меню:Client" --> "Гра:ConcreteObserver": обераєтся гра

@enduml