@startuml
scale 3
(*)  --> "Завдання вивчення\n українскій жестовій мови" as total
total --> "Навчання дактилям та жестам" as lessons
lessons --> "створення \nінтерактивних ігор"
lessons --> "створення\n позитивного\n закріплючого ефекту"
total --> "Завдання розпізновання жестів і дактилів" as recognize
recognize --> "Збір вибірки"
recognize --> "Побудова\nмоделей розпізновання"
recognize --> "Начання моделй розпізновання"
total --> "Збір статистики" as stats
stats --> "Збір ефективності\n методів розпізновання"
"Збір ефективності\n методів розпізновання" --> "Порівняння методів\n розпізновання"
stats --> "Збір ефективності навчання"
"Збір ефективності навчання" --> "Порівняння методів\n навчання"

@enduml