@startuml
scale 2
actor Дитина

Дитина -> "Гра в пари"
activate "Гра в пари"
    create Контекст
    "Гра в пари" -> Контекст
    activate Контекст
        create  "ВЗЯТИ КАРТКУ ЖЕТСТ"
        Контекст -> "ВЗЯТИ КАРТКУ ЖЕТСТ"
        activate "ВЗЯТИ КАРТКУ ЖЕТСТ"
        return
        return
    return
    loop до поки дитина грає
        Дитина --> "Гра в пари": вхідний сигнал
        activate  "Гра в пари"
            ...
            "Гра в пари" -> "Гра в пари": вихідний сигнал
            activate "Гра в пари"
                "Гра в пари" -> Контекст: надати вихідний сигнал
                 activate Контекст
            deactivate "Гра в пари"
        alt стан = ВЗЯТИ КАРТКУ ЖЕТСТ
               Контекст -> "ВЗЯТИ КАРТКУ ЖЕТСТ": обробити(this)
               activate "ВЗЯТИ КАРТКУ ЖЕТСТ"
                    "ВЗЯТИ КАРТКУ ЖЕТСТ" --> Контекст: встновити поточну картку жест
                    "ВЗЯТИ КАРТКУ ЖЕТСТ" -> "ВЗЯТИ КАРТКУ ПРЕДМЕТ" **
                    activate  "ВЗЯТИ КАРТКУ ПРЕДМЕТ"
                    return
               return "встановити стан ВЗЯТИ КАРТКУ ЖЕТСТ"

        else  стан = ВЗЯТИ КАРТКУ ПРЕДМЕТ
               activate "ВЗЯТИ КАРТКУ ПРЕДМЕТ"
                    Контекст -> "ВЗЯТИ КАРТКУ ПРЕДМЕТ": обробити(this)
                    "ВЗЯТИ КАРТКУ ПРЕДМЕТ" --> Контекст: встновити поточну картку предмет

               alt порівняти() == true
                    "ВЗЯТИ КАРТКУ ПРЕДМЕТ" -> "ВІДПОВІДЬ ВІРНА" **
                    activate "ВІДПОВІДЬ ВІРНА"
                    return
                    "ВЗЯТИ КАРТКУ ПРЕДМЕТ"  --> Контекст:  встновити стан
               else порівняти() == false
                     "ВЗЯТИ КАРТКУ ПРЕДМЕТ" -> "ВІДПОВІДЬ НЕВІРНА" **
                                        activate "ВІДПОВІДЬ НЕВІРНА"
                                        return
                                        "ВЗЯТИ КАРТКУ ПРЕДМЕТ"  --> Контекст:  встновити стан
               end
               deactivate "ВЗЯТИ КАРТКУ ПРЕДМЕТ"
        else стан = ВІДПОВІДЬ ВІРНА
             Контекст -> "ВІДПОВІДЬ ВІРНА"
             activate "ВІДПОВІДЬ ВІРНА"
                "ВІДПОВІДЬ ВІРНА" -> "ВЗЯТИ КАРТКУ ЖЕТСТ": створити
                activate "ВЗЯТИ КАРТКУ ЖЕТСТ"
                return
             return передати стан
        else стан = ВІДПОВІДЬ НЕВІРНА
          Контекст -> "ВІДПОВІДЬ НЕВІРНА"
                     activate "ВІДПОВІДЬ НЕВІРНА"
                        "ВІДПОВІДЬ НЕВІРНА" -> "ВЗЯТИ КАРТКУ ЖЕТСТ": створити
                        activate "ВЗЯТИ КАРТКУ ЖЕТСТ"
                        return
                     return передати стан
        end
        deactivate Контекст
        "Гра в пари" -> Контекст: чиЦеКінень()


        alt чиЦеКінень() == true
           activate Контекст
           return кінец гри
           return завершити гру
        else чиЦеКінень() == false
             "Гра в пари" -> Контекст: чиЦеКінень()
            activate "Гра в пари"
            activate Контекст
            return продовжити
            deactivate "Гра в пари"
             "Гра в пари" --> "Дитина": новий набір карток
        end
    end

@enduml