@startuml
  actor Дитина
  Дитина ->  "Гра в асоциації" **: обрати гру та \nпочатковий об'єкт\n для асоциації
  activate  "Гра в асоциації"
        "Гра в асоциації" -> "Генератор" **
        activate Генератор
        return
        "Гра в асоциації" -> "Генерація вірних асоциацій" **
        activate "Генерація вірних асоциацій"
        return
        "Гра в асоциації" ->  "Генератор" ++: встановити стратегію
        return
        "Гра в асоциації" ->  "Генератор" ++: сформувати набір
        "Генератор" -> СтратегіяГенерації: cгенеруватиНабір(8, карткаДляАсоціацій)
        activate СтратегіяГенерації
        return набір
        return набір
        "Гра в асоциації" -> "Генерація невірних асоциацій" **
                activate "Генерація невірних асоциацій"
                return
                "Гра в асоциації" ->  "Генератор" ++: встановити стратегію
                return
                "Гра в асоциації" ->  "Генератор" ++: сформувати набір
                "Генератор" -> СтратегіяГенерації: cгенеруватиНабір(8, карткаДляАсоціацій)
                activate СтратегіяГенерації
                return набір
                return набір
        return гра
@enduml