@startuml

scale 3
class "Гра в асоциації" as Game{
    Картка карткаДляАсоціацій;
    Картки[] вірніАссоціації;
    Картки[] невірніАсоціації;
    Контекст контекст;
    сформуватиПравила()

}

class "Генератор" as Context{
    -поточнаСтратегія
    cгенеруватиНабір(кількість, карткаДляАсоціацій)
    встановитиСтратегію()
}

class "СтратегіяГенерації" as Strategy{
    Картка cгенеруватиНабір(кількість, карткаДляАсоціацій)
}

class "Генерація вірних асоциацій" as CorrectCard{
    Картка cгенеруватиНабір(кількість, карткаДляАсоціацій)
}

class "Генерація невірних асоциацій" as WrongCard{
    Картка cгенеруватиНабір(кількість, карткаДляАсоціацій)
}

Game o-- Context
Game --> Context
Game --> CorrectCard
Game --> WrongCard
Context o-- Strategy
Strategy <|-- CorrectCard
Strategy <|-- WrongCard
Клієнт -> Game: обрана картка для асоциації


note as GameNote
сформуватиПравила:
    Генератор генератор = new Генератор(карткаДляАсоціацій)
    генератор.встановитиСтратегію(new Генерація вірних асоциацій())
    вірніАссоціації = генератор
        .cгенеруватиНабір(8, карткаДляАсоціацій)
    генератор.встановитиСтратегію(new Генерація невірних асоциацій())
    невірніАсоціації = генератор
        .cгенеруватиНабір(8, карткаДляАсоціацій)
end note
Game .. GameNote
@enduml